apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  namespace: stark-cluster
  labels:
    service: jenkins
spec:
  containers:
  - name: stark-jenkins
    image: jenkins/jenkins:lts
    resources:
      limits:
        memory: "600Mi"
      requests:
        memory: "500Mi"
    
  restartPolicy: OnFailure

---

kind: Service
apiVersion: v1
metadata:
  name: my-service
  namespace: stark-cluster
spec:
  selector:
    service: jenkins
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
