apiVersion: v1
kind: PodPreset
metadata:
  name: Jenkins-config
  namespace: stark-cluster
spec:
  selector:
    matchLabels:
      service: jenkins
  volumeMounts:
    - mountPath: /var/lib/jenkins
      name: jenkins-volume
  volumes:
    - name: jenkins-volume
      emptyDir: {}
---

apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  namespace: stark-cluster
  labels:
    service: jenkins
spec:
  containers:
  - name: stark-jenkins
    image: jenkins/jenkins:lts
    resources:
      limits:
        memory: "600Mi"
      requests:
        memory: "500Mi"
    
  restartPolicy: OnFailure

---

kind: Service
apiVersion: v1
metadata:
  name: my-service
  namespace: stark-cluster
spec:
  selector:
    service: jenkins
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---

kind: Service
apiVersion: v1
metadata:
  name: ssh
  namespace: stark-cluster
spec:
  selector:
    service: jenkins
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22  
  type: LoadBalancer
